---
- name: Install blackbox exporter
  package:
    name: "blackbox_exporter"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
...
