---
- hosts: localhost
  become: true
  vars:
    NS: TRAVIS
  roles:
    - role: users
    - role: repo
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io
    - role: role_under_test
...
